[package]
name = "advent_of_code2019"
version = "0.1.0"
authors = ["Fredrik Jansson <frjansso@cisco.com>"]
edition = "2018"

[dependencies]
itertools = "*"
lazy_static = "*"
minifb = "*"
nom = "5"
num-rational = "0.2"
pathfinding = "^1"
permutohedron = "0.2.4"
rayon = "1"
regex = "*"
